/* Optional providers load only after an explicit stored choice. */
(function(){
const key='fr_cookie_consent_v4';let started=false;
function state(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch(e){return null}}
function script(src){const s=document.createElement('script');s.async=true;s.src=src;s.crossOrigin='anonymous';document.head.append(s)}
function apply(){if(started)return;started=true;const c=state();if(c&&c.analytics){window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('config','G-0RQHSQTDG0');script('https://www.googletagmanager.com/gtag/js?id=G-0RQHSQTDG0')}if(c&&c.ads)script('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3266016041579839')}
function choose(analytics,ads){localStorage.setItem(key,JSON.stringify({essential:true,analytics:!!analytics,ads:!!ads,updated:new Date().toISOString()}));location.reload()}
function show(){let panel=document.getElementById('sharedConsent');if(panel){panel.hidden=false;return}panel=document.createElement('section');panel.id='sharedConsent';panel.setAttribute('aria-label','Cookie preferences');panel.style.cssText='position:fixed;bottom:16px;left:16px;right:16px;max-width:660px;margin:auto;z-index:99999;background:#10161d;color:#fff;border:1px solid #586574;padding:18px;border-radius:12px;font:14px/1.6 system-ui;box-shadow:0 8px 30px #0008';panel.innerHTML='<strong>Cookie preferences / Çerez tercihleri</strong><p>Optional analytics and advertising stay off until accepted. İsteğe bağlı analiz ve reklamlar kabul edilene kadar kapalıdır. <a href="/cookie-policy" style="color:#b7ff3c">Details</a></p>';[['Reject optional / Reddet',false,false],['Analytics only / Yalnızca analiz',true,false],['Accept all / Tümünü kabul et',true,true]].forEach(([label,a,b])=>{const button=document.createElement('button');button.textContent=label;button.style.cssText='margin:4px;padding:10px;border:1px solid #718096;border-radius:6px;background:#18212b;color:#fff;cursor:pointer';button.onclick=()=>choose(a,b);panel.append(button)});document.body.append(panel)}
function init(){if(typeof window.saveConsent==='function')window.saveConsent=choose;const change=document.createElement('button');change.textContent='Cookie preferences / Çerez tercihleri';change.style.cssText='display:block;margin:16px auto;padding:8px;background:transparent;color:inherit;border:1px solid #586574;border-radius:6px;cursor:pointer';change.onclick=show;(document.querySelector('.footer')||document.body).append(change);if(!state()&&!document.getElementById('cookieBanner'))show();apply()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();