/* Screen layout only: scanner selection, metrics and ordering remain untouched. */
(()=>{
 const premium=document.createElement('link');premium.rel='stylesheet';premium.href='premium-v2.css';document.head.appendChild(premium);
 const $=id=>document.getElementById(id), main=document.querySelector('main'),layout=document.querySelector('.layout');
 const intel=$('intel'), signals=$('topSignals');
 const words={en:{market:'Market',favorites:'Favorites',overview:'Overview',chart:'Chart',history:'History',back:'Back to market',heatmap:'Heatmap',guide:'How to read signals',detail:'Coin analysis',select:'Select a coin to inspect its data.',info:'About & policies',scan:'Scanner',loading:'Waiting for market data…',historyNote:'Recent scanner observations for this coin, saved on this device. Not executed trades.',noHistory:'No saved observations for this coin yet.',time:'Time',score:'Score',help:'Help'},tr:{market:'Piyasa',favorites:'Favoriler',overview:'Özet',chart:'Grafik',history:'Geçmiş',back:'Piyasaya dön',heatmap:'Isı haritası',guide:'Sinyaller nasıl okunur?',detail:'Coin analizi',select:'Verilerini incelemek için bir coin seçin.',info:'Hakkımızda ve politikalar',scan:'Tarayıcı',loading:'Piyasa verisi bekleniyor…',historyNote:'Bu coin için bu cihazda saklanan tarama gözlemleri. Gerçekleşen işlemler değildir.',noHistory:'Bu coin için henüz kayıtlı gözlem yok.',time:'Zaman',score:'Skor',help:'Yardım'}};
 const t=k=>(words[currentLang]||words.en)[k]||k;
 let tab='overview';
 // Separate the list from the detail area instead of stacking every panel.
 layout.replaceChildren(signals,intel);
  // Retain original panels before the layout changes (passed through bootstrap).
 const saved=window.frPanels;
 const heatPanel=saved.heat,helpPanel=saved.help;
 const extras=document.createElement('section');extras.id='auxView';extras.append(heatPanel,helpPanel);layout.after(extras);
 saved.score.hidden=true;saved.history.hidden=true;saved.rest.hidden=true;main.append(saved.score,saved.history,saved.rest);
 const historyPane=document.createElement('section');historyPane.id='coinHistory';
 const overview=document.createElement('section');overview.id='detailOverview';
 overview.append($('heroIntel'),$('scoreBreakdown'));
 const chartPane=document.createElement('section');chartPane.id='detailChart';chartPane.append(intel.querySelector('.chart-head'),$('coinChart'));
 // Existing render targets remain attached, even when their duplicated presentation is hidden.
 const legacy=document.createElement('div');legacy.hidden=true;legacy.append($('intelBars'),$('movers'));intel.append(legacy);
 const empty=document.createElement('p');empty.id='detailEmpty';empty.className='empty-state';
 const tabs=document.createElement('div');tabs.className='detail-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Coin analysis');
 for(const key of ['overview','chart','history']){const b=document.createElement('button');b.type='button';b.dataset.detailTab=key;b.id='tab-'+key;b.setAttribute('role','tab');b.setAttribute('aria-controls',{overview:'detailOverview',chart:'detailChart',history:'coinHistory'}[key]);b.addEventListener('click',()=>{tab=key;updateTabs()});tabs.append(b)}
 tabs.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const keys=['overview','chart','history'];let n=keys.indexOf(tab);n=e.key==='Home'?0:e.key==='End'?2:(n+(e.key==='ArrowRight'?1:2))%3;tab=keys[n];updateTabs();tabs.children[n].focus()});
 const back=document.createElement('button');back.type='button';back.className='back-market';back.addEventListener('click',()=>go('#dashboard'));
 intel.prepend(back);intel.querySelector('.detail-actions').after(tabs,empty,overview,chartPane,historyPane);
 for(const [key,pane] of Object.entries({overview,chart:chartPane,history:historyPane})){pane.setAttribute('role','tabpanel');pane.setAttribute('aria-labelledby','tab-'+key)}
 const shortcuts=document.createElement('div');shortcuts.className='market-shortcuts';shortcuts.innerHTML='<a href="#heatmapBox" data-work="heatmap"></a><a href="#guide" data-work="guide"></a>';signals.querySelector('.panel-head').replaceChildren(Object.assign(document.createElement('h2'),{id:'scannerHeading'}),shortcuts);
 const footer=document.querySelector('.footer');const disclosures=document.createElement('details');disclosures.className='footer-disclosure';const summary=document.createElement('summary');summary.dataset.work='info';disclosures.append(summary,footer);main.append(disclosures);
 document.querySelectorAll('.sidebar .side-card').forEach(n=>n.hidden=true);
 document.querySelector('.sidebar .nav').innerHTML='<a href="#dashboard" data-work="market"></a><a href="#favorites" data-work="favorites"></a><a href="tools.html" data-terminal="tools">Trading tools</a><a href="academy.html" data-terminal="academy">Academy</a><a href="#heatmapBox" data-work="heatmap"></a><a href="#guide" data-work="help"></a><a href="https://t.me/rsialertecrin" target="_blank" rel="noopener">Telegram ↗</a>';
 function go(hash){if(location.hash===hash)route();else location.hash=hash;}
 function route(){const hash=location.hash;const view=hash==='#favorites'?'favorites':hash==='#intel'?'coin':hash==='#heatmapBox'?'heatmap':hash==='#guide'||hash==='#how-to-analyze'?'guide':'market';document.body.dataset.screen=view;layout.hidden= !['coin','market'].includes(view);$('favoritesPanel').hidden=view!=='favorites';extras.hidden=!['heatmap','guide'].includes(view);heatPanel.hidden=view!=='heatmap';helpPanel.hidden=view!=='guide';document.querySelectorAll('.sidebar .nav a,.mobile-dock a').forEach(a=>{const active=a.hash===(view==='coin'?'#dashboard':view==='market'?'#dashboard':hash);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});updateTabs();}
 function updateTabs(){const has=!!allRows.find(r=>r.symbol===selectedSymbol);empty.hidden=has;empty.textContent=t('select');for(const b of tabs.children){const active=b.dataset.detailTab===tab;b.textContent=t(b.dataset.detailTab);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1}overview.hidden=!has||tab!=='overview';chartPane.hidden=!has||tab!=='chart';historyPane.hidden=!has||tab!=='history';tabs.hidden=!has;back.textContent='← '+t('back');}
 function historyView(){historyPane.replaceChildren();const note=document.createElement('p');note.textContent=t('historyNote');note.className='history-note';historyPane.append(note);let entries=[];try{entries=JSON.parse(localStorage.getItem('fr_signal_history')||'[]').filter(x=>x.symbol===selectedSymbol)}catch{}if(!entries.length){const p=document.createElement('p');p.className='empty-state';p.textContent=t('noHistory');historyPane.append(p);return}for(const e of entries){const row=document.createElement('div');row.className='coin-history-row';for(const value of [e.time,`${t('score')} ${e.score}`,`RSI ${e.rsi} · OB ${e.ob}`]){const span=document.createElement('span');span.textContent=value;row.append(span)}historyPane.append(row)}}
 function compact(){const q=$('search').value.toUpperCase();const rows=allRows.filter(r=>r.symbol.includes(q)).slice(0,12);const box=$('mobileSignals');if(!rows.length){if(!allRows.length)box.innerHTML='<p class="empty-state">'+t('loading')+'</p>';return}box.replaceChildren();for(const [i,r] of rows.entries()){const b=document.createElement('button');b.type='button';b.className='compact-signal'+(r.symbol===selectedSymbol?' selected':'');b.setAttribute('aria-label',r.symbol+', RSI '+r.rsi.toFixed(2)+', '+t('score')+' '+r.score);const name=document.createElement('span');name.className='compact-name';name.innerHTML=`<small>${String(i+1).padStart(2,'0')}</small><strong></strong>`;name.querySelector('strong').textContent=r.symbol.replace('USDT','');const price=document.createElement('span');price.className='compact-price';price.textContent=fmt(r.price,6);const metrics=document.createElement('span');metrics.className='compact-metrics';metrics.textContent=`RSI ${r.rsi.toFixed(2)}  ·  OB ${r.obCount}  ·  ${t('score')} ${r.score}`;const change=document.createElement('span');change.className='compact-change '+(r.change>=0?'green':'red');change.textContent=percent(r.change);b.append(name,price,metrics,change);b.addEventListener('click',()=>window.selectSymbol(r.symbol));box.append(b)}}
 const originalRender=window.render;window.render=function(rows){originalRender(rows);compact();historyView();updateTabs();};
 window.selectSymbol=function(symbol){if(!allRows.some(r=>r.symbol===symbol))return;selectedSymbol=symbol;window.render(allRows);$('actionNotice').textContent='';const u=new URL(location.href);u.searchParams.set('symbol',symbol);u.hash='intel';if(location.hash!=='#intel')history.pushState(null,'',u);else history.replaceState(null,'',u);route();if(matchMedia('(max-width: 900px)').matches)window.scrollTo({top:0,behavior:'instant'});};
 const setLanguage=window.setLang;window.setLang=function(lang){setLanguage(lang);labels();compact();historyView();updateTabs()};
 function labels(){document.querySelectorAll('[data-work]').forEach(n=>n.textContent=t(n.dataset.work));$('scannerHeading').textContent=t('scan');intel.querySelector('.panel-head h2').textContent=t('detail');}
 window.addEventListener('hashchange',route);window.addEventListener('popstate',route);
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',route));
 labels();compact();historyView();route();delete window.frPanels;
})();
