const BASE="https://fapi.binance.com";
const tf=["5m","15m","1h","4h"];
const j=async p=>{const r=await fetch(BASE+p);if(!r.ok)throw new Error(`${r.status} ${p}`);return r.json()};
const rsi=(c,n=14)=>{if(c.length<=n)return 50;let g=0,l=0;for(let i=c.length-n;i<c.length;i++){const d=c[i]-c[i-1];d>0?g+=d:l-=d}return l===0?100:100-100/(1+g/l)};
const ema=(a,n)=>{let e=a[0],k=2/(n+1);for(const x of a.slice(1))e=x*k+e*(1-k);return e};
const atr=(k,n=14)=>{let x=[];for(let i=1;i<k.length;i++){const h=+k[i][2],l=+k[i][3],p=+k[i-1][4];x.push(Math.max(h-l,Math.abs(h-p),Math.abs(l-p)))}return x.slice(-n).reduce((a,b)=>a+b,0)/Math.min(n,x.length)};
async function features(s,i){const k=await j(`/fapi/v1/klines?symbol=${s}&interval=${i}&limit=120`),c=k.map(x=>+x[4]),v=k.map(x=>+x[5]);const rv=rsi(c),e9=ema(c.slice(-60),9),e21=ema(c.slice(-60),21),va=v.slice(-20).reduce((a,b)=>a+b,0)/20;return{tf:i,price:c.at(-1),rsi:+rv.toFixed(2),trend:e9>e21?1:-1,volumeRatio:+(v.at(-1)/Math.max(va,1e-9)).toFixed(2),atr:+atr(k).toFixed(8)}}
async function main(){const ex=await j("/fapi/v1/exchangeInfo");const syms=ex.symbols.filter(x=>x.contractType==="PERPETUAL"&&x.quoteAsset==="USDT"&&x.status==="TRADING").map(x=>x.symbol);const tick=await j("/fapi/v1/ticker/24hr"),tm=new Map(tick.map(x=>[x.symbol,x]));const liquid=syms.filter(s=>+(tm.get(s)?.quoteVolume||0)>=5_000_000).sort((a,b)=>+(tm.get(b)?.quoteVolume||0)-+(tm.get(a)?.quoteVolume||0));let out=[];for(let p=0;p<liquid.length;p+=8){const batch=liquid.slice(p,p+8);const rows=await Promise.all(batch.map(async s=>{try{const f=await Promise.all(tf.map(i=>features(s,i))),m=f.find(x=>x.tf==="15m"),align=f.reduce((a,x)=>a+x.trend,0),long=Math.round(50+(align*7)+(m.rsi<35?12:m.rsi>70?-12:0)+(m.volumeRatio>1.5?6*m.trend:0)),score=Math.max(0,Math.min(100,long));return{symbol:s,score,long:score,short:100-score,grade:Math.max(score,100-score)>=80?"S+":Math.max(score,100-score)>=70?"S":Math.max(score,100-score)>=62?"A":"WAIT",direction:score>=50?"LONG":"SHORT",features:f,quoteVolume:+(tm.get(s)?.quoteVolume||0)} }catch(e){return{symbol:s,error:e.message}}}));out.push(...rows);await new Promise(r=>setTimeout(r,120))}
out=out.filter(x=>!x.error).sort((a,b)=>Math.max(b.long,b.short)-Math.max(a.long,a.short));console.log(JSON.stringify({generatedAt:new Date().toISOString(),universe:syms.length,liquidUniverse:liquid.length,mode:"RESEARCH_ONLY",results:out},null,2))}
main().catch(e=>{console.error(e);process.exit(1)});