const fs=require('node:fs');const vm=require('node:vm');const cp=require('node:child_process');const assert=require('node:assert/strict');
const before=cp.execFileSync('git',['show','4070f3081b7c8a2516340edbb6c9f90f0e386bed:index.html'],{encoding:'utf8'});const after=fs.readFileSync('index.html','utf8');
const engine=s=>s.slice(s.indexOf('function num('),s.indexOf('function selectSymbol('));
assert.equal(engine(after),engine(before),'Scanner source changed');assert(after.includes('setInterval(load,15000)'));
for(const match of after.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
async function simulate(source,scenario){let rendered;const requests=[];const ctx={currentLang:'en',API:'https://fapi.binance.com',FALLBACK:'https://data-api.binance.vision',apiStatus:{},sideStatus:{},selectedSymbol:null,allRows:[],tr:x=>x,console:{error:()=>{}},saveSignalHistory:()=>{},renderSignalHistory:()=>{},render:r=>rendered=r};ctx.fetch=async url=>{requests.push(url);if(scenario==='fallback'&&url.startsWith(ctx.API))return{ok:false};if(scenario==='error')return{ok:false};if(url.includes('/klines')){const i=Number(/COIN(\d+)/.exec(url)[1]);if(scenario==='partial'&&i%3===0)return{ok:false};return{ok:true,json:async()=>Array.from({length:120},(_,j)=>[j,0,0,0,100+i+j*(i%3-1)*0.2+Math.sin(j+i)*4])}}if(url.includes('exchangeInfo'))return{ok:true,json:async()=>({symbols:Array.from({length:95},(_,i)=>({symbol:`COIN${i}USDT`,contractType:i===94?'CURRENT_QUARTER':'PERPETUAL',quoteAsset:'USDT',status:i===93?'BREAK':'TRADING'}))})};return{ok:true,json:async()=>Array.from({length:95},(_,i)=>({symbol:`COIN${i}USDT`,lastPrice:100+i,priceChangePercent:(i%17)-8,quoteVolume:(95-i)*1e6}))}};vm.createContext(ctx);vm.runInContext(engine(source),ctx);await ctx.load();return JSON.parse(JSON.stringify({rows:rendered||null,requests,status:ctx.apiStatus.textContent}))}
(async()=>{for(const scenario of ['normal','fallback','partial','error']){const a=await simulate(before,scenario),b=await simulate(after,scenario);assert.deepEqual(b,a,scenario+' scanner mismatch');if(scenario!=='error')assert.equal(b.rows.length,80);console.log('PASS same scanner output and requests:',scenario)}
const {calculate:c}=require('../calculators.js');const close=(a,b)=>assert(Math.abs(a-b)<1e-8,`${a} != ${b}`);
close(c('position-sizing',{balance:1000,risk:1,entry:100,stop:95}).headline,2);
close(c('profit-loss',{entry:100,exit:110,quantity:2,fee:.05,direction:'long'}).headline,19.79);
close(c('profit-loss',{entry:100,exit:90,quantity:2,fee:.05,direction:'short'}).headline,19.81);
for(const direction of ['long','short']){const entry=100,fee=.05;const exit=c('break-even',{entry,fee,direction}).headline;close(c('profit-loss',{entry,exit,quantity:3,fee,direction}).headline,0)}
close(c('funding-cost',{notional:1000,rate:.01,periods:3,direction:'long'}).headline,.3);
close(c('funding-cost',{notional:1000,rate:-.01,periods:3,direction:'long'}).headline,-.3);
close(c('funding-cost',{notional:1000,rate:.01,periods:3,direction:'short'}).headline,-.3);
assert.throws(()=>c('position-sizing',{balance:1000,risk:1,entry:100,stop:100}));assert.throws(()=>c('break-even',{entry:100,fee:100}));assert.throws(()=>c('funding-cost',{notional:1000,rate:.01,periods:1.5}));assert.throws(()=>c('profit-loss',{entry:NaN,exit:100,quantity:1,fee:0}));console.log('PASS calculator examples, both directions, funding signs and invalid inputs');})().catch(e=>{console.error(e);process.exitCode=1});
