// DOM integration check. Requires jsdom; optionally set FR_JSDOM_PATH to its package path.
const {JSDOM,VirtualConsole}=require(process.env.FR_JSDOM_PATH||'jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
let html=fs.readFileSync('index.html','utf8');
html=html.replace(/<script\b[^>]*src="([^"]+)"[^>]*><\/script>/g,(all,src)=>['terminal.js','workspace.js','data-help.js'].includes(src)?'<script>'+fs.readFileSync(src,'utf8')+'</script>':'');
const errors=[];const consoleAdapter=new VirtualConsole();consoleAdapter.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(html,{url:'https://futuresradar.org/',runScripts:'dangerously',virtualConsole:consoleAdapter,beforeParse(w){w.setInterval=()=>0;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.matchMedia=()=>({matches:true});w.fetch=async url=>({ok:true,json:async()=>url.includes('exchangeInfo')?{symbols:Array.from({length:85},(_,i)=>({symbol:`COIN${i}USDT`,contractType:'PERPETUAL',quoteAsset:'USDT',status:'TRADING'}))}:url.includes('/klines')?Array.from({length:120},(_,i)=>[i,0,0,0,100+Math.sin(i)*3+i*.1]):Array.from({length:85},(_,i)=>({symbol:`COIN${i}USDT`,lastPrice:100+i,priceChangePercent:i%15,quoteVolume:(85-i)*1e6}))});}});
const w=dom.window,$=id=>w.document.getElementById(id),pause=()=>new Promise(r=>setTimeout(r,20));
(async()=>{await pause();assert.deepEqual(errors,[]);assert($('dataHelp'));assert($('dataHelp').textContent.includes('35'));assert.equal(w.document.body.dataset.screen,'market');assert.equal(w.document.querySelectorAll('.compact-signal').length,12);assert.equal($('signals').children.length,18);for(const id of ['recent','heatmap','marketScorePanel','whySignalPanel','signalHistoryList','intelBars','movers'])assert($(id),id+' render target detached');
const first=w.document.querySelector('.compact-signal');first.click();assert.equal(w.document.body.dataset.screen,'coin');assert.equal($('detailOverview').hidden,false);assert.equal($('detailChart').hidden,true);$('tab-chart').click();assert.equal($('detailOverview').hidden,true);assert.equal($('detailChart').hidden,false);$('tab-history').click();assert.equal($('coinHistory').hidden,false);
$('favoriteSelected').click();assert.equal(JSON.parse(w.localStorage.getItem('fr_favorites_v1')).length,1);w.location.hash='#favorites';await pause();assert.equal($('favoritesPanel').hidden,false);assert.equal(w.document.querySelector('.layout').hidden,true);$('favoritesList').querySelector('a').click();await pause();assert.equal(w.document.body.dataset.screen,'coin');assert.equal(w.document.querySelector('.layout').hidden,false);
w.document.querySelector('.back-market').click();await pause();assert.equal(w.document.body.dataset.screen,'market');w.location.hash='#heatmapBox';await pause();assert.equal($('heatmapBox').hidden,false);assert.equal($('how-to-analyze').hidden,true);w.location.hash='#guide';await pause();assert.equal($('how-to-analyze').hidden,false);
w.setLang('tr');assert.equal($('scannerHeading').textContent,'Tarayıcı');w.location.hash='#dashboard';await pause();$('search').value='NOTTHERE';$('search').dispatchEvent(new w.Event('input'));assert.equal(w.document.querySelectorAll('.compact-signal').length,0);$('search').value='';$('search').dispatchEvent(new w.Event('input'));assert.equal(w.document.querySelectorAll('.compact-signal').length,12);assert.deepEqual(errors,[]);console.log('PASS DOM: data render, compact list, coin tabs, favorites, back, heatmap, guide, language, search');dom.window.close();})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1});
